services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decentrastore-app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: decentrastore
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:7
    container_name: decentrastore-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
